import Head from 'next/head'
import Header from './inc/header'

export default function Layout({children}){
    return (
        <>
            <div>
                <Head>
                    <title>Crypto Wallet</title>
                    <meta name="description" content="Generated by create next app" />
                    <link rel="icon" href="/favicon.ico" />
                </Head>
                <Header />
                <main>{children}</main>
            </div>
        </>
    )
}